menu:
  Home: /
  Archives: /archives
  About: /about

widgets: 
- search
- category
- tag

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: false
  twitter: true
  google: true
  pinterest: false

fancybox: true

google_analytics:
rss:
